### ISSUE TITLE
Input in '' quotation are not parsed by SQLair

### ISSUE THREAD

**Issue by ycliuhw** [canonical/sqlair#148]
The problem is that if we want to use regex` or `LIKE` in SQLite, we have to quote the value.
However, I found that SQLair currently ignores any parameters in quotations.
For example, the `name_prefix` parameter in `WHERE name LIKE '$M.name_prefix%'` will be ignored by sqlair.
Then, the SQLite raises an error: `invalid input parameter: argument of type \"M\" not used by query`.

**Comment by Aflynn50** [comment]
For use cases like this I would recommend using `CONCAT`. For example you could do:
```
SELECT name FROM user WHERE name LIKE CONCAT($M.name_prefix, '%')
```
The limitation of not parsing query input parameters in quotes, either `"` or `'` applies also to regular `?` SQL query parameters. In SQLair we purposefully pass over anything contained in quotes.

**Comment by ycliuhw** [comment]
Yeah, this could be a workaround. Thanks, @Aflynn50 .

**Comment by jack-w-shaw** [comment]
Sometimes the CONCAT function isn't available, e.g. it was only recently added to SQLite/DQLite

So an alternative is to use the concat operator, `||`.
